theme = "jellybeans"

[editor]
bufferline = "multiple"
color-modes = true
true-color = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
